import type { Metadata } from "next";
import "./styles/globals.css"
import { Space_Grotesk, Staatliches } from "next/font/google"

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['500', '700'], 
  variable: '--font-space-grotesk',
})

const staatliches = Staatliches({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-staatliches',
})

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable} ${staatliches.variable}`}>
        {children}
      </body>
    </html>
  );
}
